#!/bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
X='\033[0m'

[ -z "${BASH_VERSION:-}" ] && echo -e "${RED}[*] This script must be run with bash" && exit 1

if [[ -z "$PREFIX" || -z "$TERMUX_VERSION" ]]; then
    echo -e "${RED}[*] This script must be ran in Termux${X}"
    exit 1
fi

BIN="/data/data/com.termux/files/usr/bin"
DEX_BIN="$BIN/rish_shizuku.dex"
RISH_BIN="$BIN/rish"

if [[ -f "$DEX_BIN" && -f "$RISH_BIN" ]]; then
    echo -e "${BLUE}[*] Already installed rish files${X}"
    exit 0
fi

declare -A files=(
    ["rish_shizuku.dex"]="https://github.com/duckofduckers/Shizuku-Rish-Setup/raw/main/rish_shizuku.dex"
    ["rish"]="https://github.com/duckofduckers/Shizuku-Rish-Setup/raw/main/rish"
)

for filename in "${!files[@]}"; do
    filepath="$BIN/$filename"
    url="${files[$filename]}"

    if [[ -f "$filepath" ]]; then
        echo -e "${BLUE}[*] $filename already exists, skipping${X}"
        continue
    fi

    echo -e "${YELLOW}[*] Installing $filename...${X}"
    curl -fsS -L -o "$filepath" "$url"

    if [[ "$filename" == "rish" ]]; then
        chmod +x "$filepath"
    fi

    if [[ -f "$filepath" ]]; then
        echo -e "${GREEN}[*] $filename installed successfully${X}"
    else
        echo -e "${RED}[*] $filename not installed successfully${X}"
    fi
done
